/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.muffato.form;

import br.com.muffato.dao.Configuracao;
import br.com.muffato.dao.SQLite;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gomes_cb
 */
public class ConfiguracaoForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracaoForm
     */
    public ConfiguracaoForm() {
        initComponents();
        carregarConfiguracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHost = new javax.swing.JTextField();
        txtPorta = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHostProxy = new javax.swing.JTextField();
        txtPortaProxy = new javax.swing.JTextField();
        txtLoginProxy = new javax.swing.JTextField();
        txtSenhaProxy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAssinatura = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCorpoEmail = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("HOST");

        jLabel2.setText("PORTA");

        jLabel3.setText("EMAIL");

        jLabel4.setText("SENHA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("EMAIL");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("PROXY");

        jLabel7.setText("HOST");

        jLabel8.setText("PORTA");

        jLabel9.setText("LOGIN");

        jLabel10.setText("SENHA");

        jLabel11.setText("Assinatura");

        txtAssinatura.setColumns(20);
        txtAssinatura.setRows(5);
        jScrollPane1.setViewportView(txtAssinatura);

        jLabel12.setText("Empresa");

        txtCorpoEmail.setColumns(20);
        txtCorpoEmail.setRows(5);
        jScrollPane2.setViewportView(txtCorpoEmail);

        jLabel13.setText("Texto");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Resetar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorta)
                    .addComponent(txtEmail)
                    .addComponent(txtSenha)
                    .addComponent(txtHostProxy)
                    .addComponent(txtPortaProxy)
                    .addComponent(txtLoginProxy)
                    .addComponent(txtSenhaProxy)
                    .addComponent(txtNomeEmpresa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                    .addComponent(txtHost)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel6)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHostProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPortaProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoginProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenhaProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String valorEmail = txtEmail.getText();
        String valorSenha = txtSenha.getText();
        String valorHost = txtHost.getText();
        String valorPorta = txtPorta.getText();
        
        String valorHostProxy = txtHostProxy.getText();
        String valorPortaProxy = txtPortaProxy.getText();
        String valorLoginProxy = txtLoginProxy.getText();
        String valorSenhaProxy = txtSenhaProxy.getText();
        String valorAssinatura = txtAssinatura.getText();
        String valorNomeEmpresa = txtNomeEmpresa.getText();
        String valorTexto = txtCorpoEmail.getText();
        
        
        SQLite.getConn().update(Configuracao.EMAIL, valorEmail);
        SQLite.getConn().update(Configuracao.SENHA, valorSenha);
        SQLite.getConn().update(Configuracao.HOST, valorHost);
        SQLite.getConn().update(Configuracao.PORTA, valorPorta);
        
        SQLite.getConn().update(Configuracao.HOST_PROXY, valorHostProxy);
        SQLite.getConn().update(Configuracao.PORTA_PROXY, valorPortaProxy);
        SQLite.getConn().update(Configuracao.LOGIN_PROXY, valorLoginProxy);
        SQLite.getConn().update(Configuracao.SENHA_PROXY, valorSenhaProxy);
        
        SQLite.getConn().update(Configuracao.ASSINATURA, valorAssinatura);
        SQLite.getConn().update(Configuracao.NOME_EMPRESA, valorNomeEmpresa);
        SQLite.getConn().update(Configuracao.TEXTO_EMAIL, valorTexto);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SQLite.getConn().update(Configuracao.TEXTO_EMAIL, 
             "Bom dia, 	   \n" +
                "	   \n" +
                "Prezado cliente,	   \n" +
                "	   \n" +
                "Estamos entrando em contato para lembra-lo de que sua empresa tem um boleto em aberto conosco	   \n" +
                "que foi enviado junto a DANFE no ato da entrega da mercadoria, conforme informações descriminadas abaixo 	   \n" +
                "Caso tenha alguma dúvida ou divergencia sobre o documento,  por favor entrar em contato 	   \n" +
                "	   \n" +
                "Razão Social 	_RAZAO_   \n" +
                "CnpJ	_CNPJ_   \n" +
                "Nota Fiscal	_NOTA_FISCAL_   \n" +
                "Emissão	_EMISSAO   \n" +
                "Venc	_VCTO_   \n" +
                "Valor	R$ _VALOR_   \n" +
                "	   \n" +
                "Caso o pagamento já tenha sido efetuado, por favor desconsiderar a mensagem 	   \n" +
                "	\n" +
                "Cordialmente"   
                
        );
        
        txtCorpoEmail.setText( "Bom dia, 	   \n" +
                "	   \n" +
                "Prezado cliente,	   \n" +
                "	   \n" +
                "Estamos entrando em contato para lembra-lo de que sua empresa tem um boleto em aberto conosco	   \n" +
                "que foi enviado junto a DANFE no ato da entrega da mercadoria, conforme informações descriminadas abaixo 	   \n" +
                "Caso tenha alguma dúvida ou divergencia sobre o documento,  por favor entrar em contato 	   \n" +
                "	   \n" +
                "Razão Social 	_RAZAO_   \n" +
                "CnpJ	_CNPJ_   \n" +
                "Nota Fiscal	_NOTA_FISCAL_   \n" +
                "Emissão	_EMISSAO   \n" +
                "Venc	_VCTO_   \n" +
                "Valor	R$ _VALOR_   \n" +
                "	   \n" +
                "Caso o pagamento já tenha sido efetuado, por favor desconsiderar a mensagem 	   \n" +
                "	\n" +
                "Cordialmente");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracaoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAssinatura;
    private javax.swing.JTextArea txtCorpoEmail;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtHostProxy;
    private javax.swing.JTextField txtLoginProxy;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtPorta;
    private javax.swing.JTextField txtPortaProxy;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSenhaProxy;
    // End of variables declaration//GEN-END:variables

    public void carregarConfiguracoes() {
        SQLite dbCon;
        try {
            dbCon = new SQLite("base.db");
            dbCon.initDB();
            Iterator it = dbCon.getAll().iterator();
            Configuracao hs;

            while (it.hasNext()) {
                hs = (Configuracao) it.next();

                System.out.println("Chave:" + hs.getChave());
                System.out.println("Valor:" + hs.getValor());

                if (hs.getChave().equals(Configuracao.EMAIL)) {
                    txtEmail.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.SENHA)) {
                    txtSenha.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.HOST)) {
                    txtHost.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.PORTA)) {
                    txtPorta.setText(hs.getValor());
                }
                
                if (hs.getChave().equals(Configuracao.HOST_PROXY)) {
                    txtHostProxy.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.PORTA_PROXY)) {
                    txtPortaProxy.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.LOGIN_PROXY)) {
                    txtLoginProxy.setText(hs.getValor());
                }
                if (hs.getChave().equals(Configuracao.SENHA_PROXY)) {
                    txtSenhaProxy.setText(hs.getValor());
                }
                
                if (hs.getChave().equals(Configuracao.ASSINATURA)) {
                    txtAssinatura.setText(hs.getValor());
                }
                
                if (hs.getChave().equals(Configuracao.NOME_EMPRESA)) {
                    txtNomeEmpresa.setText(hs.getValor());
                }
                
                if (hs.getChave().equals(Configuracao.TEXTO_EMAIL)) {
                    txtCorpoEmail.setText(hs.getValor());
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ConfiguracaoForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConfiguracaoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
